version: '3.8'

services:
  app:
    image: stiggee/lernwortspiel
    ports:
      - "443:443"
    environment:
      SPRING_APPLICATION_NAME: lernwortspiel
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wortspiel
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 280211
      SPRING_MAIL_HOST: smtp.strato.de
      SPRING_MAIL_PORT: 465
      SPRING_MAIL_USERNAME: support@lernwortspiel.de
      SPRING_MAIL_PASSWORD: Streamkill280211
      SPRING_MAIL_PROTOCOL: smtps
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 280211
      MYSQL_DATABASE: wortspiel
    ports:
      - "3306:3306"
    volumes:
      - ./lernwortspiel.sql:/docker-entrypoint-initdb.d/lernwortspiel.sql # Подключаем дамп

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
