version: '3.8'
services:
  db:
    image: mysql:8
    container_name: lernwortspiel_db
    environment:
      MYSQL_ROOT_PASSWORD: 280211
      MYSQL_DATABASE: wortspiel
      MYSQL_USER: jpa
      MYSQL_PASSWORD: 280211
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-dumps:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lernwortspiel_app
    ports:
      - "8080:8080"
      - "443:443" # Открываем порт 443 для SSL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/wortspiel
      - SPRING_DATASOURCE_USERNAME=jpa
      - SPRING_DATASOURCE_PASSWORD=280211
    depends_on:
      db:
        condition: service_healthy



volumes:
  db_data:

